# Text2Scene Config with Controlnet + DreamBooth finetuning for American Psycho
runs_dir: output
seed: 13
frames: 5  # SPEED: Reduced from 10 for much faster testing

# DreamBooth Model Configuration
stable_diffusion_checkpoint: "camgitblame/american_psycho_sd15"
use_dreambooth_unet: true  # Enable hybrid approach for non-inpainting DreamBooth model

# ControlNet Configuration (NEW: Required for structural consistency with non-inpainting models)
use_controlnet: true  # Enable ControlNet for better geometry preservation
controlnet_model: "lllyasviel/control_v11p_sd15_inpaint"  # Inpainting-specific ControlNet
controlnet_conditioning_scale: 0.8  # SPEED: Reduced from 1.0 for faster inference

# Scene Prompting
inpainting_prompt: "POV, walkthrough, apartment from sks americanpsycho, masterpiece, indoor scene, best quality"

# SPEED OPTIMIZATIONS: Aggressive settings for fastest testing
num_inpainting_steps: 10  # SPEED: Reduced from 20 for much faster generation
classifier_free_guidance_scale: 6.0  # SPEED: Reduced from 7.5 for faster inference
inpainting_resolution: 512  # SPEED: Reduced from base 600 to minimize computation
antialiasing_factor: 1  # SPEED: Disabled antialiasing (base is 2)
use_xformers: true  # SPEED: Enable for better memory efficiency and speed
finetune_decoder: false  # SPEED: Disable decoder finetuning
finetune_depth_model: false  # SPEED: Disable depth model finetuning
motion: round  # SPEED: Use round motion for predictable, simple camera path
camera_speed_factor: 0.05  # SPEED: Faster camera movement for quicker testing

# DTYPE FIX: Disable mixed precision to prevent float/half type conflicts
enable_mix_precision: false  # FIXED: Prevent data type mismatch errors in hybrid approach
