# SPEED-OPTIMIZED: DreamBooth Non-Inpainting + ControlNet
# FAST TEST: 30-frame generation with finetuning disabled for speed
# Uses NON-INPAINTING DreamBooth model with hybrid inpainting approach

runs_dir: output
seed: 13
frames: 30  

# DreamBooth Model Configuration (NON-INPAINTING ONLY)
stable_diffusion_checkpoint: "camgitblame/american_psycho_sd15_1500"
use_dreambooth_unet: true

# ControlNet Configuration 
use_controlnet: true  # Enable ControlNet for better geometry preservation
controlnet_model: "lllyasviel/control_v11p_sd15_inpaint"  # Inpainting-specific ControlNet
controlnet_conditioning_scale: 0.8  # Full structural consistency
classifier_free_guidance_scale: 8.0  # Stronger prompt adherence

# Scene Prompting - ENHANCED for style and geometric consistency
inpainting_prompt: "sks americanpsycho, POV walkthrough, Patrick Bateman's luxury apartment, consistent lighting, architectural photography, modern minimalist interior, sks americanpsycho style, masterpiece, best quality, sharp details"
negative_inpainting_prompt: "blurry, low quality, distorted geometry, warped perspective, floating objects, inconsistent depth, geometric artifacts, deformed architecture, fisheye distortion, curved lines"
# SPEED OPTIMIZATIONS
num_inpainting_steps: 35  
inpainting_resolution: 600
use_xformers: true  # ENABLED: Better memory efficiency and speed
enable_mix_precision: false  # DISABLED: Prevent data type conflicts with DreamBooth
finetune_decoder: false  # DISABLED: Skip decoder finetuning for speed
finetune_depth_model: false  # DISABLED: Skip depth model finetuning for speed

# GEOMETRY FIXES CONFIGURATION
enable_warp_fix: true  # Enable geometry improvement patches
warp_fix_overrides:
  fix_inpaint_strength: 0.5  # Conservative inpainting strength (0.3-1.0)
  fix_mask_op: "erode"  # Conservative mask operation: erode, dilate, or both
  fix_mask_iters: 2  # Number of morphological operations
  fix_depth_cn_scale: 0.8  # Depth ControlNet conditioning scale (0.5-1.5)
  fix_depth_ema_alpha: 0.7  # Temporal depth smoothing factor (0.0-1.0)
