# DreamBooth + 2 ControlNet for The Shining
runs_dir: output
seed: 13
frames: 30

# DreamBooth Model Configuration
stable_diffusion_checkpoint: "camgitblame/the_shining"
use_dreambooth_unet: true

# ControlNet Inpainting Configuration
use_controlnet: true
controlnet_model: "lllyasviel/control_v11p_sd15_inpaint"
controlnet_conditioning_scale: 0.85
classifier_free_guidance_scale: 8

# Scene Prompting
inpainting_prompt: "POV, walkthrough, sks theshining, Overlook Hotel hallway, masterpiece, indoor scene, best quality"



# SPEED OPTIMIZATIONS
num_inpainting_steps: 35
inpainting_resolution: 600
use_xformers: true
enable_mix_precision: false
finetune_decoder: false
finetune_depth_model: false

# CONFIGURATION 

enable_warp_fix: true
warp_fix_overrides:
  fix_depth_cn_scale: 0.60 # CN Depth
  fix_inpaint_strength: 0.46      
  fix_mask_op: "erode"
  fix_mask_iters: 2
  fix_depth_cn_scale: 0.60        
  fix_depth_ema_alpha: 0.75       
